export interface FeedSchoolDTO {
  idAluno?: string | null,
  idMensagem?: number | null,
  tipo?: number | null,
  data?: string | null,
  remetente?: string | null,
  sumario?: string  | null,
  corpoMensagem?: string | null,
  corpoMensagemHtml?: string | null,
  html?: boolean | null,
  imagemUrl?: string | null,
  urlPublica?: string | null,
  openImagemUrl?: string | null,
  modoResposta?: number | null,
  resposta?: string | null,
  tipoResposta?: string | null,
  temAnexo?: string | null,
  idEvento?: string | null,
  status?: string | null,
  todosUsuarios?: string | null,
  dataAlteracao?: string | null,
  dataExpiracao?: string | null,
  dataExpiracaoFormatada?: string | null,
  statusExpiracao?: boolean | null,
  pendenciaDataExpiracao?: string | null,
  pendenciaDataResposta?: string | null,
  pendenciaTipoPendencia?: string | null,
  pendenciaStatus?: string | null,
  pendenciaResposta?: string | null,
  pendenciaPendente?: string | null,
  gudMensagem?: string | null,
  interacoes?: {
    permiteCurtir?: boolean | null,
    curtiu?: boolean | null,
    qtdeCurtidas?: number | null,
    permiteResponder?: boolean | null,
    respondeu?: boolean | null,
    idCanal?: number | null,
    idAtendente?: number | null,
    textoBotaoResponder?: string | null,
  },
  idGrupoCobranca?: number | null,
  idCobranca?: number | null ,
  video?: number | null
}